apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-config
  namespace: default
data:
  kibana.yml: |
    server.name: kibana
    server.host: "0"
    elasticsearch.hosts: [ "http://elasticsearch:9200" ]
